### ISSUE TITLE
native-complete requires manual setup of native-complete-at-point

### ISSUE THREAD

**Issue by piater** [CeleritasCelery/emacs-native-shell-complete#10]
For me, installing and activating `native-complete` from Melpa had no effect. It turned out that `native-complete-at-point` was not hooked into `completion-at-point-functions`. In fact, I did not find any code in the package to do so. I then customized `shell-mode-hook` to include `(lambda nil (add-hook (quote completion-at-point-functions) (function native-complete-at-point) nil t))` (in the customization interface), which made it work like a charm.

It took me quite a while to figure out the problem and then the solution; it would be nice to automate or at least document this. One obstacle was an accidental omission in the [README](https://github.com/CeleritasCelery/emacs-native-shell-complete/blob/master/README.org): It says 

>  provides which

where it should say

>  provides `native-complete-at-point` which

**Comment by CeleritasCelery** [comment]
Thanks!
