### ISSUE TITLE
No candidates and "command not found"

### ISSUE THREAD

**Issue by cpitclaudel** [CeleritasCelery/emacs-native-shell-complete#3]
This package looks great, but I'm running into issues (I don't get completions).

To debug I set PS1 to `$` to run out prompt issues, typed "test", and called `(native-complete-at-point)`.  Then I get this in native-complete--buffer:

```
test* echo : command not found
```

Any idea? Thanks!

**Comment by CeleritasCelery** [comment]
my first guess would be that "test" is not the start of a valid command. If you try to tab-complete "test" in a full featured terminal does that work correctly?

But I think the bigger question here is "How to debug when I am not getting candidates?"

Here is my flow when debugging this package.

1. evaluate `(comint-simple-send (get-buffer-process (current-buffer)) "test\t\x15")` in the buffer. This will tell you if tab completion is enabled. if not, make sure `(native-complete-setup-bash)` was executed before you ran your shell. 

2. If tab completion works in the basic sense. evaluate `(native-complete-get-completion-style)` on an empty prompt. This will tell you which completion style is being used.

3. If using bash (which it looks like you are), make sure that command echoing is off with `stty -echo`

4. If you get to this point execute `(native-complete--get-prefix)` where you would expect a completion. This will show you the command that is run. Try that same command in a full-featured terminal to make sure you get the results you expect. 


Try out the steps above and let me know the results. I hope to make the package more robust based on your feedback.

**Comment by cpitclaudel** [comment]
> my first guess would be that "test" is not the start of a  valid command. If you try to tab-complete "test" in a full featured  terminal does that work correctly?

Yes, it does work:

```
$ test
test      testdisk  testparm  
```

> evaluate (comint-simple-send (get-buffer-process (current-buffer)) "test\t\x15") in the buffer. This will tell you if tab completion is enabled. if not, make sure (native-complete-setup-bash) was executed before you ran your shell.

```
$ PS1="$ "
$ echo $TERM
vt50
$ stty -echo
$ 
```

Running `(comint-simple-send (get-buffer-process (current-buffer)) "test\t\x15")` returns `nil`.

> If tab completion works in the basic sense. evaluate (native-complete-get-completion-style) on an empty prompt. This will tell you which completion style is being used.

`(native-complete-get-completion-style)` returns `bash`

> If you get to this point execute (native-complete--get-prefix) where you would expect a completion. This will show you the command that is run. Try that same command in a full-featured terminal to make sure you get the results you expect.

This returns `"test*' echo '"`, which does seem to work in a regular shell:

```
$ test*' echo '
test testdisk testparm 
```

And M-x company-native-complete does work too, now! Maybe I missed one of the previous steps earlier.  In fact, it works very nicely!  Good job.

I think the debugging process above would make a good addition to the readme.
Feel free to close if the results above are all as expected (I was a bit surprised by the `nil`)

**Comment by CeleritasCelery** [comment]
> Running (comint-simple-send (get-buffer-process (current-buffer)) "test\t\x15") returns nil.

It is supposed to return `nil`. That command is only to generate output in your shell.
